spring:
  application:
    name: pulsegrid
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: pulsegrid-materializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: dev.noorps.pulsegrid.model
    listener:
      ack-mode: record

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

pulsegrid:
  api-keys: ${TENANT_API_KEYS:demo:demo-local-key}
  topics:
    telemetry: telemetry.events.v1
    dead-letter: telemetry.events.v1.dlt
